### ISSUE TITLE
Esboçar certificiado final

### ISSUE THREAD

**Issue by Kerooker** [dasiusp/CLEBER#1]
Precisa conter:
- [ ] Nome do participante
- [ ] Natureza do evento/atividade
- [ ] Data da participação
- [ ] Carga horária da atividade
- [ ] Token gerado com explicação de uso (vide exemplo do Jupiter Web)

<details>
<summary> Exemplo de documento "assinado" pelo Jupiter Web via Token (clique para expandir)</summary>
<img src='https://user-images.githubusercontent.com/1577251/58095520-94581200-7ba9-11e9-8a62-371c82e630b8.jpg' />
</details>

<details>
<summary> Exemplos de certificados de participação em atividades (clique para expandir)</summary>
<img src='https://user-images.githubusercontent.com/1577251/58095588-bce00c00-7ba9-11e9-8210-e8c287de9b59.jpg' />

<img src='https://user-images.githubusercontent.com/1577251/58095603-c79aa100-7ba9-11e9-9d7b-6540faaef7be.jpg' />
</details>

**Comment by gi-armani** [comment]
Protótipo de certificado nois

**Comment by gi-armani** [comment]
[certificado.pdf](https://github.com/dasiusp/CLEBER/files/3212712/certificado.pdf)
Protótipo de certificado

**Comment by gi-armani** [comment]
[Certificado de participação.docx](https://github.com/dasiusp/CLEBER/files/3224391/Certificado.de.participacao.docx)
